import { nanoid } from "nanoid";

export const trains = [
  {
    id: nanoid(),
    name: "Aachen",
    date: "2003-07-03",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Aalen",
    date: "2008-06-21",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Altenbeken",
    date: "2003-07-11",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Altenburg",
    date: "2009-06-27",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Amsterdam",
    date: "2003-10-06",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Andernach",
    date: "2009-10-17",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ansbach",
    date: "2022-12-05",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Arnhem",
    date: "2003-03-20",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Arnstadt",
    date: "2004-05-01",
    type: "ICE_T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Aschaffenburg",
    date: "2015-02-23",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Augsburg",
    date: "2002-11-21",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bad Hersfeld",
    date: "2003-12-06",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bad Oeynhausen",
    date: "2006-05-17",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bad Oldesloe",
    date: "2004-03-03",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Baden-Baden",
    date: "2003-11-05",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bamberg",
    date: "2007-11-28",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Basel",
    date: "2016-06-21",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bautzen/Budyšin",
    date: "2004-06-02",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bebra",
    date: "2003-07-19",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bergen auf Rügen",
    date: "2005-07-09",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bergisch Gladbach",
    date: "2006-11-02",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Berlin",
    date: "2004-12-12",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bielefeld",
    date: "2002-11-15",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bingen am Rhein",
    date: "2012-03-24",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bitterfeld-Wolfen",
    date: "2009-07-25",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bochum",
    date: "2003-07-09",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bonn",
    date: "2002-12-17",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Brandenburg an der Havel",
    date: "2004-05-11",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Braunschweig",
    date: "2002-11-12",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bremen",
    date: "2002-12-12",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bremerhaven",
    date: "2003-11-13",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Bruchsal",
    date: "2003-07-23",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Brussel/Bruxelles",
    date: "2016-11-28",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Castrop-Rauxel",
    date: "2013-11-13",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Celle",
    date: "2008-11-29",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Chur",
    date: "2015-12-13",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Coburg",
    date: "2006-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Cottbus/Chóśebuz",
    date: "2002-12-07",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Crailsheim",
    date: "2004-10-19",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Darmstadt",
    date: "2006-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Delitzsch",
    date: "2004-10-09",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Dessau",
    date: "2002-12-12",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Dillingen a.d. Donau",
    date: "2019-12-02",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Dortmund",
    date: "2002-11-28",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Dresden",
    date: "2002-12-20",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Duisburg",
    date: "2003-10-08",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Düsseldorf",
    date: "2002-12-09",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Eberswalde",
    date: "2007-05-12",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Eisenach",
    date: "2003-05-13",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ellwangen",
    date: "2014-03-29",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Elsterwerda",
    date: "2011-06-19",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Erfurt",
    date: "2002-11-21",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Erlangen",
    date: "2004-06-30",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Essen",
    date: "2002-11-20",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Esslingen am Neckar",
    date: "2017-06-11",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Euregio Maas-Rhein",
    date: "2020-02-17",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Europa/Europe",
    date: "2019-05-22",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Falkenberg/Elster",
    date: "2009-08-15",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Flensburg",
    date: "2008-09-26",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Fontanestadt Neuruppin",
    date: "2006-03-18",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Forbach-Lorraine",
    date: "2007-01-20",
    type: "ICE 3MF",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Frankenthal/Pfalz",
    date: "2005-05-19",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Frankfurt (Oder)",
    date: "2003-06-21",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Freiburg im Breisgau",
    date: "2003-01-29",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Freie und Hansestadt Hamburg",
    date: "2002-11-06",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Freilassing",
    date: "2008-07-18",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Friedrichshafen",
    date: "2005-06-14",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Fulda",
    date: "2015-03-21",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Fürth",
    date: "2007-09-15",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Garmisch-Partenkirchen",
    date: "2006-02-18",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Geisenheim/Rheingau",
    date: "2005-11-10",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Gelnhausen",
    date: "2016-06-03",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Gelsenkirchen",
    date: "2004-09-07",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Gießen",
    date: "2004-07-13",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Görlitz",
    date: "2003-12-03",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Goslar",
    date: "2017-06-09",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Gotha",
    date: "2006-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Göttingen",
    date: "2003-01-22",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Güstrow",
    date: "2003-06-21",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Gütersloh",
    date: "2004-07-14",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hagen",
    date: "2003-07-19",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Halle (Saale)",
    date: "2006-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hamm (Westf.)",
    date: "2003-09-27",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hanau",
    date: "2004-07-05",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hannover",
    date: "2003-01-08",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hansestadt Greifswald",
    date: "2006-11-30",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hansestadt Lübeck",
    date: "2004-02-20",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hansestadt Rostock",
    date: "2006-09-12",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hansestadt Stralsund",
    date: "2003-05-25",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hansestadt Warburg",
    date: "2014-06-28",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hansestadt Wismar",
    date: "2004-12-12",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Heidelberg",
    date: "2002-12-05",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Heppenheim/Bergstraße",
    date: "2008-08-22",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Herford",
    date: "2006-05-17",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hildesheim",
    date: "2008-06-13",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Hof",
    date: "2005-10-06",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Homburg/Saar",
    date: "2006-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Horb am Neckar",
    date: "2006-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ilmenau",
    date: "2007-09-01",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ingolstadt",
    date: "2003-11-27",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Innsbruck",
    date: "2009-12-12",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Interlaken",
    date: "2007-12-07",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Itzehoe",
    date: "2006-02-10",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Jena",
    date: "2002-11-27",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Jever",
    date: "2017-04-29",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Jüterbog",
    date: "2007-04-28",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Kaiserslautern",
    date: "2006-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Karlsruhe",
    date: "2002-12-18",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Kassel",
    date: "2002-12-17",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Kiel",
    date: "2002-11-20",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "København",
    date: "2007-12-07",
    type: "ICE-TD",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Koblenz",
    date: "2003-03-29",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Köln",
    date: "2006-04-13",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Konstanz",
    date: "2008-04-19",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Krefeld",
    date: "2003-11-21",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Landhut",
    date: "2007-07-07",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Leipzig",
    date: "2002-12-13",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Leverkusen",
    date: "2009-06-20",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Lichtenfels",
    date: "2004-07-27",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Limburg an der Lahn",
    date: "2006-11-08",
    type: "ICE 3MF",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Linz am Rhein",
    date: "2011-06-18",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Linz",
    date: "2008-10-22",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Lübbenau/Spreewald",
    date: "2004-03-27",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ludwigshafen am Rhein",
    date: "2004-02-10",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ludwigslust",
    date: "2004-08-21",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Lüneburg",
    date: "2003-08-13",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Lutherstadt Wittenberg",
    date: "2002-11-26",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Magdeburg",
    date: "2002-11-25",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Mainz",
    date: "2007-01-02",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Mannheim",
    date: "2003-02-24",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Marburg",
    date: "2017-08-15",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Markt Holzkirchen",
    date: "2007-05-26",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Meiningen",
    date: "2005-10-01",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Meißen",
    date: "2003-11-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Memmingen",
    date: "2004-02-20",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Minden",
    date: "2003-06-22",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Mittenwald",
    date: "2015-09-26",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Mönchengladbach",
    date: "2011-03-29",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Montabaur",
    date: "2006-09-17",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Mühldorf a. Inn",
    date: "2015-03-21",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Mühlhausen/Thüringen",
    date: "2015-09-05",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Mühlheim an der Ruhr",
    date: "2008-10-28",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "München",
    date: "2003-01-10",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Münster (Westf.)",
    date: "2003-07-10",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Murnau am Staffelsee",
    date: "2015-06-27",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Nauen",
    date: "2007-12-01",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Naumburg (Saale)",
    date: "2003-11-22",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Neu-Isenburg",
    date: "2011-05-26",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Neu-Ulm",
    date: "2015-06-06",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Neubrandenburg",
    date: "2003-09-30",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Neumünster",
    date: "2003-08-20",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Neustadt an der Weinstraße",
    date: "2003-06-26",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Neustrelitz",
    date: "2008-10-25",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Nördlingen",
    date: "2021-06-28",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Nürnberg",
    date: "2016-08-20",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Oberhausen",
    date: "2004-09-02",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Oberursel (Taunus)",
    date: "2019-02-21",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Offenbach am Main",
    date: "2003-08-26",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Offenburg",
    date: "2003-11-22",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Oldenburg (Oldb)",
    date: "2009-06-27",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Oschatz",
    date: "2006-03-30",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Osnabrück",
    date: "2003-06-19",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ostseebad Binz",
    date: "2011-06-17",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ostseebad Warnemünde",
    date: "2007-06-12",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Paderborn",
    date: "2003-06-25",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Paris",
    date: "2017-06-01",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Passau",
    date: "2004-09-14",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Pforzheim",
    date: "2004-07-01",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Pirna",
    date: "2003-06-14",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Plattling",
    date: "2006-02-10",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Plauen/Vogtland",
    date: "2004-03-11",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Potsdam",
    date: "2003-03-19",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Prenzlau",
    date: "2013-05-04",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Quedlinburg",
    date: "2004-05-04",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Rathenow",
    date: "2006-07-15",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ravensburg",
    date: "2004-04-15",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Recklinghausen",
    date: "2003-07-15",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Regensburg",
    date: "2004-02-20",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Rendsburg",
    date: "2016-06-21",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Reutlingen",
    date: "2004-11-30",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Rheinsberg",
    date: "2005-10-15",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Riesa",
    date: "2003-08-30",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Rödental",
    date: "2012-10-12",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Rosenheim",
    date: "2003-04-28",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Rüdesheim am Rhein",
    date: "2022-01-14",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Saalfeld (Saale)",
    date: "2004-06-19",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Saarbrücken",
    date: "2005-07-07",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Salzburg",
    date: "2006-12-09",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Schaffhausen",
    date: "2008-07-10",
    type: "ICE 3M",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Schwäbisch Hall",
    date: "2007-04-28",
    type: "ICE 3MF",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Schwerin",
    date: "2003-10-03",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Schwerte (Ruhr)",
    date: "2011-09-16",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Siegburg",
    date: "2003-07-22",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Siegen",
    date: "2011-09-18",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Singen (Hohentwiel)",
    date: "2008-06-07",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Solingen",
    date: "2003-07-02",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Sonneberg",
    date: "2008-09-27",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "St. Ingberg",
    date: "2008-05-10",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Stendal",
    date: "2003-01-13",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Stuttgart",
    date: "2002-11-19",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Templin",
    date: "2006-03-25",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Timmendorfer Strand",
    date: "2007-11-16",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Torgau",
    date: "2007-01-02",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Traunstein",
    date: "2010-08-01",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Travemünde",
    date: "2008-12-13",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Treuchtlingen",
    date: "2004-09-22",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Trier",
    date: "2004-05-11",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Tuttlingen",
    date: "2015-07-25",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Tutzing",
    date: "2010-07-21",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Uelzen",
    date: "2008-08-30",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Ulm",
    date: "2002-11-18",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Vaihingen an der Enz",
    date: "2010-07-03",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Villingen-Schwenningen",
    date: "2012-09-15",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Waren (Müritz)",
    date: "2006-05-20",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Weil am Rhein",
    date: "2016-05-29",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Weilheim i. OB",
    date: "2017-06-26",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Weimar",
    date: "2003-01-17",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Westerland/Sylt",
    date: "2017-06-21",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Wien",
    date: "2007-12-08",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Wiesbaden",
    date: "2002-12-15",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Wittenberge",
    date: "2004-08-24",
    type: "ICE-T",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Wolfsburg",
    date: "2003-01-23",
    type: "ICE 3",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Worms",
    date: "2006-09-12",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Wuppertal",
    date: "2003-07-01",
    type: "ICE 2",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Würzburg",
    date: "2006-07-17",
    type: "ICE 3MF",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Zürich",
    date: "2006-01-20",
    type: "ICE 1",
    isSeen: false,
  },
  {
    id: nanoid(),
    name: "Zwickau",
    date: "2004-07-31",
    type: "ICE 2",
    isSeen: false,
  },
];
